[build]
  # Публикуем только папку bot (изолированный контент сайта)
  publish = "bot"
  command = ""

# Редирект для SPA/статических ссылок, чтобы все пути работали
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Если сайт будет как SPA, раскомментируйте редирект ниже
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200


